### PR TITLE
Audit gating

### PR DESCRIPTION
**Pull request by dandersonsw**
## Changes proposed in this pull request:

- Updates audit script to pass/fail based on audit report results
- Send email on pass/fail with audit results

## Things to check

- For any logging statements, is there any chance that they could be logging sensitive data?
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of sensitive data.

## Security considerations

Gating on whether an image passes the container hardening audit meets compliance requirements. This works with the current pipeline, but can also be shifted to work with our new plans.

### CODE REVIEW

**Review by rcgottlieb — APPROVED** [review]

**Comment by jameshochadel** [comment]
These look like great changes, thanks @dandersonsw. Just as a preview I'm hoping we can move these to be steps in the `common-pipelines` repository once I merge the skeleton of the new `container` pipeline. Let's chat architecture next week.

**Comment by pburkholder** [comment]
The `usg audit` command also creates a file `/var/lib/usg/usg-results-2YYYYMMDD-HHMM.xml`. In that file you can grep for `urn:xccdf:scoring:default`:

```text
grep urn:xccdf:scoring:default /var/lib/usg/usg-results-20230713.2138.xml
  <model system="urn:xccdf:scoring:default"/>
    <score system="urn:xccdf:scoring:default" maximum="100.000000">79.975197</score>
```

If the score is not 100, then we fail (?) -- maybe there's lower threshold someplace. 

Anyhow, we don't need `bs4` and post scan you should remove the `/var/lib/usg/*results*` since each file is 8Mb.

**Comment by jameshochadel** [comment]
@pburkholder I hesitate to use grep here because regular expressions [famously](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags) aren't sufficient in the general case for parsing XML. (They have a regular grammar, which is strictly less capable than XML's context-free grammar.) Of course, this is a specific case, but I'd rather take advantage of the structure of HTML to build a solution here that's more robust than text parsing. 

The trade-off is adding a 3rd party dependency. @dandersonsw mentions a different possibility [here](https://github.com/cloud-gov/product/issues/2539#issuecomment-1636311719). What are the specific concerns about `bs4`? Its provenance, probability of being maintained, possibility of use as a supply chain attack vector? Would use of a different 3rd party library ameliorate the concerns?

**Comment by pburkholder** [comment]
Yeah I was thinking about the [ALL IS LOŚ͖̩͇̗̪̏̈́T ALL I​S LOST](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags) answer.  But here, you're not "Parsing XML" in the sense of "I need to match all of these opening tags..." - you're just looking for a simple pre-generated string to determine the pass/fail score, so a regex is fine, I think.

Also, I was wanting to keep things simple. It seems we're using `bs4` to determine the "score" from the report, but the score has already been computed by the tool, so why not use it, instead of stepping through all the divs from ` divs = soup.findAll('div', {"class": "progress-bar"})`?

Anyhow, I don't need to bring this to a halt. If it seems fine to y'all, then: onwards.

**Pull request merged**
